### ISSUE TITLE
Make a questionnaire template

### ISSUE THREAD

**Issue by bkopplin** [HJamison/CourseworkAC31007Agile#17]

**Comment by Arcfej** [comment]
These type of questions are used a lot: https://www.researchgate.net/figure/The-System-Usability-Scale-SUS-questionnaire_fig6_271336759
Make sure that Microsoft Form can do that. If not, we should use something else.

**Comment by Arcfej** [comment]
The questionnaires must be filled out anonymously and must be able to do it without login.
